name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.k3v1nn90 }}
          password: ${{ secrets.P00pP00pP00p }}
          repository: https://hub.docker.com/repository/docker/k3v1nn90/project5
          tag_with_ref: true
